config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :bookings
  resources :users
  resources :performances
  resources :schedules
  #resources :transactions
  resources :stages

  get '/', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy', as: 'logout'
  get '/home', to: 'sessions#index'

  get '/search', to: 'bookings#find_friend'

  get '/schedules/:id/share', to: 'schedules#share_schedule', as: 'share'

  get '/analytics', to: 'analytics#index', as: 'analytics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :schedule
  has_many :bookings, through: :schedule
  has_many :performances, through: :bookings
  has_many :artists, through: :performances
  has_many :stages, through: :performances

  validates :username, uniqueness: true
  validates :username, :first_name, :last_name, :gender, presence: true
  validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :age, numericality: { only_integer: true, greater_than: 0, less_than: 120 }
  validates :username, length: { minimum: 3 }
  validates :password, length: { in: 6..20 }
  validates :password, confirmation: true

  def self.all_names
    self.all.map(&:username)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.valid?
      @user.schedule = Schedule.create(name: "#{@user.first_name}'s awesome schedule'")
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def edit
    authorized_for_user(@user)
  end

  def update
    @user.update(user_params)

    if @user.valid?
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    @user.destroy
    redirect_to login_path
  end


  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :gender, :age, :first_name, :last_name, :schedule, :password, :password_confirmation)
  end

end

app/views/users/new.html.erb
<head>
  <style>
    h2 {
        text-align: center;
        font-family: Alba Super;
    }
    h3 {
        color: Red;
        text-align: center;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
    }
    label {
        color: DeepSkyBlue;
        /* background-color: rgba(255,255,255,0.5); */
    }

    form {
        text-align: center;
        font-family: verdana;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
    }

    div {
        vertical-align:  left;
        font-family: verdana;
    }

  </style>
</head>

<body background="https://static01.nyt.com/images/2014/06/10/arts/music/20140610-GOVBALL-slide-IBHG/20140610-GOVBALL-slide-IBHG-master1050.jpg">

<h2><div><span style="color:#ff0000;">C</span><span style="color:#ff2a00;">r</span><span style="color:#ff5500;">e</span><span style="color:#ff7f00;">a</span><span style="color:#ff9f00;">t</span><span style="color:#ffbf00;">e</span><span style="color:#ffdf00;"> </span><span style="color:#ffff00;">a</span><span style="color:#aaff00;"> </span><span style="color:#55ff00;">N</span><span style="color:#00ff00;">e</span><span style="color:#00ff40;">w</span><span style="color:#00ff80;"> </span><span style="color:#00ffbf;">U</span><span style="color:#00ffff;">s</span><span style="color:#00aaff;">e</span><span style="color:#0055ff;">r</span><span style="color:#0000ff;">:</span></div></h2>
<%= form_for @user do |f| %>
  <%= f.label :username, "Username:" %>
  <div><%= f.text_field :username %><br /></div>
  <%= f.label :first_name %>
  <div><%= f.text_field :first_name %></div><br />
  <%= f.label :last_name %>
  <div><%= f.text_field :last_name %></div><br />
  <%= f.radio_button :gender, "Male" %>
  <%= f.label :gender, "Male" %>
  <%= f.radio_button :gender, "Female" %>
  <%= f.label :gender, "Female" %><br />
  <%= f.label :age %>
  <div><%= f.number_field :age %></div><br />
  <%= f.label :password %>
  <div><%= f.password_field :password %></div><br />
  <%= f.label :password_confirmation, "Retype your password:" %>
  <div><%= f.password_field :password_confirmation %></div><br />
  <%= button_tag(type: "submit", class: "btn btn-primary btn-lg", name: "create", value: "conceal") do %>
    <span class="glyphicon glyphicon-user"></span> Create User
  <% end %><br />
<% end %>

<% if flash[:errors] %>
  <% if flash[:errors].class == String %>
      <%= flash[:errors] %>
  <% else %>
    <% flash[:errors].each do |error| %>
      <h3><%= error %></h3>
    <% end %>
  <% end %>
<% end  %>

</body>

app/views/users/show.html.erb
<head>
  <style>
    h2 {
        color: DeepSkyBlue;
        /* background-color: rgba(255,255,255,0.5); */
    }
    label {
        color: DeepSkyBlue;
        /* background-color: rgba(255,255,255,0.5); */
    }
  </style>
</head>

<body background="https://www.edmsauce.com/wp-content/uploads/2017/01/Gov-Ball-2016.jpg">

<h2>Welcome, <%= @user.first_name %>!</h2>

<label>Your schedule: <%= link_to @user.schedule.name, schedule_path(@user.schedule) %></label>

</body>