config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :bookings
  resources :users
  resources :performances
  resources :schedules
  #resources :transactions
  resources :stages

  get '/', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy', as: 'logout'
  get '/home', to: 'sessions#index'

  get '/search', to: 'bookings#find_friend'

  get '/schedules/:id/share', to: 'schedules#share_schedule', as: 'share'

  get '/analytics', to: 'analytics#index', as: 'analytics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  has_many :performances
  has_many :artists, through: :performances
  has_many :bookings, through: :performances

  def sorted_performances
    self.performances.sort_by {|el| el.start_time}
  end
end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
  before_action :find_user, only: [:index, :show, :edit, :update, :destroy]

  def index
    @stages = Stage.all
  end

  def show
  end

  # def new
  #   @stage = Stage.new
  # end
  #
  # def create
  #   @stage = Stage.create(stage_params)
  #   if @stage.valid?
  #     redirect_to @stage
  #   else
  #     flash[:errors] = @stage.errors.full_messages
  #     redirect_to new_stage_path
  #   end
  # end
  #
  # def edit
  # end
  #
  # def update
  #   @stage.update(stage_params)
  #   if @stage.valid?
  #     redirect_to @stage
  #   else
  #     flash[:errors] = @stage.errors.full_messages
  #     redirect_to edit_stage_path(@stage)
  #   end
  # end
  #
  # def destroy
  #   @stage.destroy
  #   redirect_to stages_path
  # end
  #
  private
  #
  # def stage_params
  #   params.require(:stage).permit(:name, :venue_id)
  # end
  #
  def find_user
    @user = User.find(session[:user_id])
  end

  # def find_stage
  #   @stage = Stage.find(params[:id])
  # end

end

app/views/stages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        font-size: 16px;
        font-family: verdana;
        background-color: rgba(255,255,255,0.5);
        color: black;
    }

    h1 {
        color: Red;
        text-align: center;
        font-family: Alba Super;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
    }

    h2 {
        color: DeepSkyBlue;
        font-family: Alba Super;
        text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;
    }

  </style>
</head>

<body background="https://static1.squarespace.com/static/54f74f23e4b0952b4e0011c0/t/5a864c819140b70db7702c42/1518750862653/Atmosphere_GovBallFireWorks-AliveCoverage.JPG">

     <br>

  <h1><div><span style="color:#ff0000;">P</span><span style="color:#ff2a00;">e</span><span style="color:#ff5500;">r</span><span style="color:#ff7f00;">f</span><span style="color:#ff9f00;">o</span><span style="color:#ffbf00;">r</span><span style="color:#ffdf00;">m</span><span style="color:#ffff00;">a</span><span style="color:#aaff00;">n</span><span style="color:#55ff00;">c</span><span style="color:#00ff00;">e</span><span style="color:#00ff40;"> </span><span style="color:#00ff80;">S</span><span style="color:#00ffbf;">t</span><span style="color:#00ffff;">a</span><span style="color:#00aaff;">g</span><span style="color:#0055ff;">e</span><span style="color:#0000ff;">s</span></div></h1>

  <table>
    <tr>
      <th>Stage</th>
      <th>Artist</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Add Performance</th>
    </tr>


    <tr>
      <% @stages.each do |stage| %>
        <tr>
          <% stage.sorted_performances.each do |performance| %>
            <td> <%= stage.name %> </td>
            <td> <%= performance.artist.name %> </td>
            <td> <%= performance.start_time.strftime("%A at %l:%m%p") %> </td>
            <td> <%= performance.end_time.strftime("%A at %l:%m%p") %> </td>
            <td> <%= button_to  bookings_path(:performance_id => performance, :schedule_id => @user.schedule), class: 'btn btn-success'  do %>
              <i class="glyphicon glyphicon-plus"></i> Add to My Schedule
            <% end %> </td>

          </tr>
          <% end %>
      <% end %>
      <% if flash[:errors] %>
          <% flash[:errors].each do |error| %>
              <%= error %>
          <% end %>
      <% end  %>
      <br>
    </tr>
  </tr>
  </table>

</body>

</html>