config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :bookings
  resources :users
  resources :performances
  resources :schedules
  #resources :transactions
  resources :stages

  get '/', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy', as: 'logout'
  get '/home', to: 'sessions#index'

  get '/search', to: 'bookings#find_friend'

  get '/schedules/:id/share', to: 'schedules#share_schedule', as: 'share'

  get '/analytics', to: 'analytics#index', as: 'analytics'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Festival Manager</title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/home"><b>Music Festival Planner</b></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%=link_to "Schedule", current_user.schedule if current_user != nil %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Performances" if current_user != nil %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to"Artists", artists_path if current_user != nil %></li>
              <li><%=link_to"Stages", stages_path if current_user != nil %></li>
              <li><%=link_to"Performance Times", performances_path if current_user != nil %></li>
            </ul>
          </li>
        </ul>

        <% if logged_in? %>
          <div class="form-group">
            <%= form_tag "/search", class: "navbar-form navbar-left", method: "get" do %>
              <%= text_field_tag :friend_name %>
              <%= submit_tag "Search By Username", class: "btn btn-default" %>
            <% end %>
          </div>
        <% end %>


        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Analytics", analytics_path if current_user != nil %></li>
          <li><%= button_to"Log Out", logout_path, class: "btn btn-default", method: "post" if logged_in? %></li>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<%= yield %>

</body>
</html>